language: php
php:
- 5.6
before_script:
- cp app/config/parameters.yml.dist app/config/parameters.yml
- composer self-update
- composer install --dev --no-interaction --prefer-source
- app/console cache:warmup --env=test --quiet
script:
- "./vendor/phpunit/phpunit/phpunit --verbose --debug -c app/"
env:
  global:
  - secure: "x/5NDwghuvtVNnAwn60pMs82npJW/sRKqNdThwJXYNeCmlk0s8X2KRt1TeuiJqe/4BK9Eh8SmBzCTqUe4zl190Cx+TytrZWc7F+M+kPOfC05ueeYDx1wp9XKsd232DmPrDq0TnwKJNCEjotn+0jsJwmNF5Hdbkgi1R3bM/g8OHcpIAuJSuoizSNibyJMT4L38fGgqluCX7l3UtSvk4br4EBqjBlREHYcjRFGd/URc9v/8l7bGZHT+IXR5j1bRXyQVE7nAnxQtkPpvXFCUM1GBcXk0GoDwD5nfVP0ydaQ+JrvmECDELWWXadgspPeg00z8G2vf+UiAig/ht+ocQT7hPnME7O0Khxokw3DkyiZcQhV5wVEzKWyHN7vS35PysU1Ij4JAOFoTRbS8aPmI6STzHFcoqsKdfkq1wPmJ2oY5YGOPZOdU3tfk7h6FvLfZBIzut3ObPLi7YJLyBqmZEm0Eb46rYbUzY0D0iPZW1ERECfoypPmq8suCW/c+3O6lu2S8aMTxpHScSkjfb9AgKNQ28ssEc2n6qNToXHMBmGkMeJfqBYGBlDLo+QjxIadykn7Da0WuDXTnxFA/RfD396KDbaq3W/n0AUG+S0+XrZBVjM9OA52i5A2eWj1O6y0+WAGsbNMqoGJ47j9f8T14xEHoMvX91gVq7TH/d+Xj8kLUnM="
notifications:
  slack:
    secure: sXa05NZZZ7MVj17NFQ5XlcyFSJxLdgHYAIZedIog3qxf6f7GLXqDeaAwKb5Zg0Ib3XsyGLziZusO0uGXz4XO0CcTI+kgdtg1ena/LMTaCsWmaHfCsJzuH2+mnSchFKkXjOfMICrEmiCBWQaQgE4nmtJu1xlXXnVSIfhOUMPKGxbD3jSIibqB8EYz22pu0eZde0DwO7ipr6fxY1MAHfdM89b/d3Iqu7GaB3NIlo+ZJBfdMWWYm1D+CskmdxhJ4nXrag+oRZ5nQjm/JBcmBOwuebppc2WsSdHcQNe5YpOwSz9UcZgPjT+WafdNtHX4qTOlHjNdUx7PU8A617t728V3cLfIi9UGPRMQfxBoObj0zq/0QUhpaFJXaDoZN4olLOSaN4jZ5+lglJ72jnCnx8ijvyd5LjOdbkoPgkFI0VvklorKY+yR7tiVH67FlWFnCryK40QMBgrJE1M25D2J4DM0mSM+qR2bftmjGn8CeiGDaazn9i0AnnvexzfUGxS1LeNDsJt/i4PRglb6CUVZKaxHwnDBFVTetQWvqsAJ7HSaqH5cJ55yHtjrlMZtomtPqrWai7fhuB/oHbviMlMzJhqxLCbP2TflYTYh4MHWAXkGCFeVp3IZW5l2LAcVXFh+CgjVQNYo+u4vwlLAvjlBJ0XU3GFcqgQSSP3Mp1PIm9YKZc4=
