language: php

php:
  - 5.6

before_script:
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - composer self-update
    - composer install --dev --no-interaction --prefer-source
    - app/console cache:warmup --env=test --quiet

script:
    - ./vendor/phpunit/phpunit/phpunit --verbose --debug -c app/
