language: php
php:
- 5.6
before_script:
- cp app/config/parameters.yml.dist app/config/parameters.yml
- composer self-update
- composer install --dev --no-interaction --prefer-source
- app/console cache:warmup --env=test --quiet
script:
- "./vendor/phpunit/phpunit/phpunit --verbose --debug -c app/"
env:
  global:
  - secure: w9ADXOQH2B4MqmXnzMgSD+qLQgfdS6OtA99N1RqtEUvKZBrGpbzLsxyKwCmMbPGBXv2zknV8hbvbN18AYK1mXINFyZe01WyV6nABKjjt50spuB5W0sRS936D3Qa5fQTwCtQpgIIVQgO2ca2lSie3ufQcrze2aZoANmlWHb9k5R1a2IzNpLBaibS1szfCu1TvdRUtV3mhnQfGZ1iFIs7yLnztr4g5Gn/UTkrPwyBtUT1LDC0gB7RNYi/I2dYicx5tAeTc740fQrdSjhw4Snx6CTWm3z57CdA7fSe0ks4NHgYSH8+szBP1piGlWYpfl8/h7oJL0oj+p/1KKkVX3gMusZTl+6iD50bY2HJm74VIr4N0/cV3yj/5w9EP9KBxJCH98iGYl16ARxw+94xoEGHqObYALi+ifBbhcHLu+h+etCEho5/ayxA4gioF7x0vxg02qOpKfUB3JVR/uD4r0M/WX5cES2ehzTBL05QzkMmOFSBO43GmP/BB+fWMMHiYLMBVaK4FvjbJcggtv346mDcTX7mHb3WPoEeqZKl/tON1xCVVzaYsAJA0r/AM/ZzyK8C2Ncxom1IvLaPF0Zgfz/BRWTejfkcM+E8ZSORyXUqxTZBbjsdgYrpX4AoWVCY094oC5QHZOEHx2Ida5yQax+7rua9lWHOmclSTKWo8j5Qs9S0=
notifications:
  slack:
    secure: sXa05NZZZ7MVj17NFQ5XlcyFSJxLdgHYAIZedIog3qxf6f7GLXqDeaAwKb5Zg0Ib3XsyGLziZusO0uGXz4XO0CcTI+kgdtg1ena/LMTaCsWmaHfCsJzuH2+mnSchFKkXjOfMICrEmiCBWQaQgE4nmtJu1xlXXnVSIfhOUMPKGxbD3jSIibqB8EYz22pu0eZde0DwO7ipr6fxY1MAHfdM89b/d3Iqu7GaB3NIlo+ZJBfdMWWYm1D+CskmdxhJ4nXrag+oRZ5nQjm/JBcmBOwuebppc2WsSdHcQNe5YpOwSz9UcZgPjT+WafdNtHX4qTOlHjNdUx7PU8A617t728V3cLfIi9UGPRMQfxBoObj0zq/0QUhpaFJXaDoZN4olLOSaN4jZ5+lglJ72jnCnx8ijvyd5LjOdbkoPgkFI0VvklorKY+yR7tiVH67FlWFnCryK40QMBgrJE1M25D2J4DM0mSM+qR2bftmjGn8CeiGDaazn9i0AnnvexzfUGxS1LeNDsJt/i4PRglb6CUVZKaxHwnDBFVTetQWvqsAJ7HSaqH5cJ55yHtjrlMZtomtPqrWai7fhuB/oHbviMlMzJhqxLCbP2TflYTYh4MHWAXkGCFeVp3IZW5l2LAcVXFh+CgjVQNYo+u4vwlLAvjlBJ0XU3GFcqgQSSP3Mp1PIm9YKZc4=
