language: php

php:
  - 7.0

services:
  - mysql

git:
  submodules: false

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer self-update
  - composer install --no-interaction --prefer-source
  - app/console doctrine:database:create --env=test --no-interaction --quiet
  - app/console doctrine:schema:create  --env=test --no-interaction --quiet
  - app/console cache:warmup --env=test --quiet

script:
  - ./vendor/phpunit/phpunit/phpunit -c app/
  - ./bin/php-cs-fixer fix --diff --dry-run -v

notifications:
  slack:
    secure: sXa05NZZZ7MVj17NFQ5XlcyFSJxLdgHYAIZedIog3qxf6f7GLXqDeaAwKb5Zg0Ib3XsyGLziZusO0uGXz4XO0CcTI+kgdtg1ena/LMTaCsWmaHfCsJzuH2+mnSchFKkXjOfMICrEmiCBWQaQgE4nmtJu1xlXXnVSIfhOUMPKGxbD3jSIibqB8EYz22pu0eZde0DwO7ipr6fxY1MAHfdM89b/d3Iqu7GaB3NIlo+ZJBfdMWWYm1D+CskmdxhJ4nXrag+oRZ5nQjm/JBcmBOwuebppc2WsSdHcQNe5YpOwSz9UcZgPjT+WafdNtHX4qTOlHjNdUx7PU8A617t728V3cLfIi9UGPRMQfxBoObj0zq/0QUhpaFJXaDoZN4olLOSaN4jZ5+lglJ72jnCnx8ijvyd5LjOdbkoPgkFI0VvklorKY+yR7tiVH67FlWFnCryK40QMBgrJE1M25D2J4DM0mSM+qR2bftmjGn8CeiGDaazn9i0AnnvexzfUGxS1LeNDsJt/i4PRglb6CUVZKaxHwnDBFVTetQWvqsAJ7HSaqH5cJ55yHtjrlMZtomtPqrWai7fhuB/oHbviMlMzJhqxLCbP2TflYTYh4MHWAXkGCFeVp3IZW5l2LAcVXFh+CgjVQNYo+u4vwlLAvjlBJ0XU3GFcqgQSSP3Mp1PIm9YKZc4=
