language: php

php:
  - 7.0

services:
  - mysql

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer self-update
  - composer install --dev --no-interaction --prefer-source
  - app/console doctrine:database:create --env=test --no-interaction --quiet
  - app/console doctrine:schema:create  --env=test --no-interaction --quiet
  - app/console cache:warmup --env=test --quiet

script:
  - "./vendor/phpunit/phpunit/phpunit --verbose --debug -c app/"

env:
  global:
  - secure: x/5NDwghuvtVNnAwn60pMs82npJW/sRKqNdThwJXYNeCmlk0s8X2KRt1TeuiJqe/4BK9Eh8SmBzCTqUe4zl190Cx+TytrZWc7F+M+kPOfC05ueeYDx1wp9XKsd232DmPrDq0TnwKJNCEjotn+0jsJwmNF5Hdbkgi1R3bM/g8OHcpIAuJSuoizSNibyJMT4L38fGgqluCX7l3UtSvk4br4EBqjBlREHYcjRFGd/URc9v/8l7bGZHT+IXR5j1bRXyQVE7nAnxQtkPpvXFCUM1GBcXk0GoDwD5nfVP0ydaQ+JrvmECDELWWXadgspPeg00z8G2vf+UiAig/ht+ocQT7hPnME7O0Khxokw3DkyiZcQhV5wVEzKWyHN7vS35PysU1Ij4JAOFoTRbS8aPmI6STzHFcoqsKdfkq1wPmJ2oY5YGOPZOdU3tfk7h6FvLfZBIzut3ObPLi7YJLyBqmZEm0Eb46rYbUzY0D0iPZW1ERECfoypPmq8suCW/c+3O6lu2S8aMTxpHScSkjfb9AgKNQ28ssEc2n6qNToXHMBmGkMeJfqBYGBlDLo+QjxIadykn7Da0WuDXTnxFA/RfD396KDbaq3W/n0AUG+S0+XrZBVjM9OA52i5A2eWj1O6y0+WAGsbNMqoGJ47j9f8T14xEHoMvX91gVq7TH/d+Xj8kLUnM=
  - secure: eslLTC/DRsR74H2IvG/CS2Fnw6PQPsgs5Ie/bY6EK6YvEsW91gYD7k3R1zf5qx5468JwyNfOKDWisxD+C5b8D/tDk6WymWFU8lkoxMOBWGGHiKIHdYHtk3Bt9la8PmD3mMkiRl3tmrh2RXnfB9YauuCmhG8L0WvRj7T4A6loimRil3dCA4j0bp+E/VslPvFBJE5CJb3wTMqrpD8rjv2LAV1VHgt0dj1YXfjnAUd3JSwbaSP0jeJUQBA6UJWhIzLojUO+weXgnxsYQp2WJvTIHWmc+Z235RcRybez+A2HmianiuP4j7fEidOD48DBzM5vKrmIt+I6jZrhRap5uADKH4si5F2syjww4Gq9ImQaaXkY46z0U0nklNnHptSez0QiKEfP+mBd9EtzUtXgwuK649hr6YIKNB//VT6sZtNv9V3pvVaT1+LtwNmqwdkpkJsB/xvohbbD2jukror5eVSOjcGz1nzx3oeyONuhN3mJU0Z2ayavSZmv4r/r65v9OaXPef1SC9n2l73YFvTPKbbehXMSieTKJDAnLpX70GS+yOykTyWOIG8I+FC2P2ifzTl0vTJtmy7MZ1b3f0weWmzvikJWWsjUKP90SI7Qh9By0xMfn6u9LDOzCZejneqhO0BCHxP+3P5w4pEnwgDzhHw7kawx3+eSnhNsDIi7O5G2+Wk=
notifications:
  slack:
    secure: sXa05NZZZ7MVj17NFQ5XlcyFSJxLdgHYAIZedIog3qxf6f7GLXqDeaAwKb5Zg0Ib3XsyGLziZusO0uGXz4XO0CcTI+kgdtg1ena/LMTaCsWmaHfCsJzuH2+mnSchFKkXjOfMICrEmiCBWQaQgE4nmtJu1xlXXnVSIfhOUMPKGxbD3jSIibqB8EYz22pu0eZde0DwO7ipr6fxY1MAHfdM89b/d3Iqu7GaB3NIlo+ZJBfdMWWYm1D+CskmdxhJ4nXrag+oRZ5nQjm/JBcmBOwuebppc2WsSdHcQNe5YpOwSz9UcZgPjT+WafdNtHX4qTOlHjNdUx7PU8A617t728V3cLfIi9UGPRMQfxBoObj0zq/0QUhpaFJXaDoZN4olLOSaN4jZ5+lglJ72jnCnx8ijvyd5LjOdbkoPgkFI0VvklorKY+yR7tiVH67FlWFnCryK40QMBgrJE1M25D2J4DM0mSM+qR2bftmjGn8CeiGDaazn9i0AnnvexzfUGxS1LeNDsJt/i4PRglb6CUVZKaxHwnDBFVTetQWvqsAJ7HSaqH5cJ55yHtjrlMZtomtPqrWai7fhuB/oHbviMlMzJhqxLCbP2TflYTYh4MHWAXkGCFeVp3IZW5l2LAcVXFh+CgjVQNYo+u4vwlLAvjlBJ0XU3GFcqgQSSP3Mp1PIm9YKZc4=
