const Constants = {
    FETCH_DAILY_TWEET: 'FETCH_DAILY_TWEET',
    DAILY_TWEET_RECEIVED: 'DAILY_TWEET_RECEIVED',
    DOING_IMPORT: 'DOING_IMPORT',
    DONE_IMPORT: 'DONE_IMPORT'
}

export default Constants
