const Constants = {
    AJAX_FETCH_START:  'AJAX_FETCH_START',
    FETCH_SINGLE_DATE: 'FETCH_SINGLE_DATE',
    DOING_IMPORT:      'DOING_IMPORT',
    DONE_IMPORT:       'DONE_IMPORT',
    SET_CURRENT_DATE_AND_INDEX:  'SET_CURRENT_DATE_AND_INDEX'
}

export default Constants
