<?php

namespace AppBundle\Repository;

use AppBundle\Entity\PastTimeline;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * PastTimelineRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PastTimelineRepository extends EntityRepository
{
    public function insert(User $user, array $json, \DateTime $date)
    {
        $pastTimeLine = new PastTimeline();
        $pastTimeLine->setUser($user);
        $pastTimeLine->setTimeline($json);
        $pastTimeLine->setDate($date);
        $now = new \DateTime();
        $pastTimeLine->setCreateAt($now);
        $pastTimeLine->setUpdateAt($now);

        $this->_em->persist($pastTimeLine);
        $this->_em->flush();
    }
}
