security:
    providers:
        oauth_user_provider:
             id: oauth_entity_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            anonymous: true
            oauth:
                resource_owners:
                  twitter:   "/login/check-twitter"
                login_path:   /
                failure_path: /
                oauth_user_provider:
                    service: oauth_entity_user_provider
                default_target_path: /home

    access_control:
        - { path: ^/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/home, roles: ROLE_OAUTH_USER }
