# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
imports:
    - { resource: parameters.yml }

parameters:
#    parameter_name: value

services:
    # TODO: not service
    http_client:
        class: AppBundle\API\HTTPClient

    # TODO: not service
    twitter_api_client:
        class: AppBundle\API\TwitterAPIClient
        arguments: ["@http_client", "%twitter_api%"]

    twitter_api:
        class: AppBundle\Service\TwitterAPIService
        arguments: ["@doctrine", "@twitter_api_client"]

    oauth_entity_user_provider:
        class: AppBundle\Service\OAuthEntityUserProvider
        arguments: ["@doctrine", AppBundle\Entity\User, {twitter: twitterId}]

    app.service.common_service:
        class: AppBundle\Service\CommonService

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
