# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
imports:
    - { resource: parameters.yml }

parameters:
#    parameter_name: value

services:
    app.service.httpclient:
        class: AppBundle\Service\HTTPClient

    twitter_api:
        class: AppBundle\Service\TwitterAPI
        arguments: ["@doctrine", "@app.service.httpclient", "%twitter_api%", "@app.service.common_service"]

    oauth_entity_user_provider:
        class: AppBundle\Service\OAuthEntityUserProvider
        arguments: ["@doctrine", AppBundle\Entity\User, {twitter: twitterId}]

    app.service.common_service:
        class: AppBundle\Service\CommonService

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
