<?php

namespace AppBundle\Tests\DataFixtures;

class MyFakerProvider
{
    public function timeline()
    {
        return  [
            0 => [
                    'created_at' => 'Sat Jan 21 11:52:08 +0000 2017',
                    'id' => 822773772499308545,
                    'id_str' => '822773772499308545',
                    'text' => 'Bundle::build()とExtension::load()がそれぞれ呼ばれるタイミング分からなく混乱している #Symfony2',
                    'truncated' => false,
                    'entities' => [
                            'hashtags' => [
                                    0 => [
                                            'text' => 'Symfony2',
                                            'indices' => [
                                                    0 => 59,
                                                    1 => 68,
                                                ],
                                        ],
                                ],
                            'symbols' => [
                                ],
                            'user_mentions' => [
                                ],
                            'urls' => [
                                ],
                        ],
                    'source' => '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
                    'in_reply_to_status_id' => null,
                    'in_reply_to_status_id_str' => null,
                    'in_reply_to_user_id' => null,
                    'in_reply_to_user_id_str' => null,
                    'in_reply_to_screen_name' => null,
                    'user' => [
                            'id' => 1664570156,
                            'id_str' => '1664570156',
                            'name' => 'Ryota Murakami',
                            'screen_name' => 'malloc007',
                            'location' => '東京都',
                            'description' => 'webエンジニアです。プログラミングについてのつぶやきが多いです。 IIDX中伝 4123-1440',
                            'url' => 'https://t.co/gc9H0nrlan',
                            'entities' => [
                                    'url' => [
                                            'urls' => [
                                                    0 => [
                                                            'url' => 'https://t.co/gc9H0nrlan',
                                                            'expanded_url' => 'http://ryota-murakami.github.io/',
                                                            'display_url' => 'ryota-murakami.github.io',
                                                            'indices' => [
                                                                    0 => 0,
                                                                    1 => 23,
                                                                ],
                                                        ],
                                                ],
                                        ],
                                    'description' => [
                                            'urls' => [
                                                ],
                                        ],
                                ],
                            'protected' => false,
                            'followers_count' => 279,
                            'friends_count' => 417,
                            'listed_count' => 21,
                            'created_at' => 'Mon Aug 12 08:50:15 +0000 2013',
                            'favourites_count' => 431,
                            'utc_offset' => 32400,
                            'time_zone' => 'Tokyo',
                            'geo_enabled' => true,
                            'verified' => false,
                            'statuses_count' => 6300,
                            'lang' => 'ja',
                            'contributors_enabled' => false,
                            'is_translator' => false,
                            'is_translation_enabled' => false,
                            'profile_background_color' => '94D487',
                            'profile_background_image_url' => 'http://abs.twimg.com/images/themes/theme1/bg.png',
                            'profile_background_image_url_https' => 'https://abs.twimg.com/images/themes/theme1/bg.png',
                            'profile_background_tile' => false,
                            'profile_image_url' => 'http://pbs.twimg.com/profile_images/418236904778104833/Fvp3hQiE_normal.jpeg',
                            'profile_image_url_https' => 'https://pbs.twimg.com/profile_images/418236904778104833/Fvp3hQiE_normal.jpeg',
                            'profile_banner_url' => 'https://pbs.twimg.com/profile_banners/1664570156/1388550465',
                            'profile_link_color' => '3B94D9',
                            'profile_sidebar_border_color' => '000000',
                            'profile_sidebar_fill_color' => '000000',
                            'profile_text_color' => '000000',
                            'profile_use_background_image' => true,
                            'has_extended_profile' => true,
                            'default_profile' => false,
                            'default_profile_image' => false,
                            'following' => null,
                            'follow_request_sent' => null,
                            'notifications' => null,
                            'translator_type' => 'none',
                        ],
                    'geo' => null,
                    'coordinates' => null,
                    'place' => null,
                    'contributors' => null,
                    'is_quote_status' => false,
                    'retweet_count' => 0,
                    'favorite_count' => 0,
                    'favorited' => false,
                    'retweeted' => false,
                    'lang' => 'ja',
                ],
            1 => [
                    'created_at' => 'Sat Jan 21 04:36:26 +0000 2017',
                    'id' => 822664126002364416,
                    'id_str' => '822664126002364416',
                    'text' => 'RT @Hiraku: “アプリファーストの影で頑張るWebの話 // Speaker Deck” https://t.co/2R5bmFVLZQ',
                    'truncated' => false,
                    'entities' => [
                            'hashtags' => [
                                ],
                            'symbols' => [
                                ],
                            'user_mentions' => [
                                    0 => [
                                            'screen_name' => 'Hiraku',
                                            'name' => 'Hiraku',
                                            'id' => 5707002,
                                            'id_str' => '5707002',
                                            'indices' => [
                                                    0 => 3,
                                                    1 => 10,
                                                ],
                                        ],
                                ],
                            'urls' => [
                                    0 => [
                                            'url' => 'https://t.co/2R5bmFVLZQ',
                                            'expanded_url' => 'http://htn.to/ec6kpX',
                                            'display_url' => 'htn.to/ec6kpX',
                                            'indices' => [
                                                    0 => 50,
                                                    1 => 73,
                                                ],
                                        ],
                                ],
                        ],
                    'source' => '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
                    'in_reply_to_status_id' => null,
                    'in_reply_to_status_id_str' => null,
                    'in_reply_to_user_id' => null,
                    'in_reply_to_user_id_str' => null,
                    'in_reply_to_screen_name' => null,
                    'user' => [
                            'id' => 1664570156,
                            'id_str' => '1664570156',
                            'name' => 'Ryota Murakami',
                            'screen_name' => 'malloc007',
                            'location' => '東京都',
                            'description' => 'webエンジニアです。プログラミングについてのつぶやきが多いです。 IIDX中伝 4123-1440',
                            'url' => 'https://t.co/gc9H0nrlan',
                            'entities' => [
                                    'url' => [
                                            'urls' => [
                                                    0 => [
                                                            'url' => 'https://t.co/gc9H0nrlan',
                                                            'expanded_url' => 'http://ryota-murakami.github.io/',
                                                            'display_url' => 'ryota-murakami.github.io',
                                                            'indices' => [
                                                                    0 => 0,
                                                                    1 => 23,
                                                                ],
                                                        ],
                                                ],
                                        ],
                                    'description' => [
                                            'urls' => [
                                                ],
                                        ],
                                ],
                            'protected' => false,
                            'followers_count' => 279,
                            'friends_count' => 417,
                            'listed_count' => 21,
                            'created_at' => 'Mon Aug 12 08:50:15 +0000 2013',
                            'favourites_count' => 431,
                            'utc_offset' => 32400,
                            'time_zone' => 'Tokyo',
                            'geo_enabled' => true,
                            'verified' => false,
                            'statuses_count' => 6300,
                            'lang' => 'ja',
                            'contributors_enabled' => false,
                            'is_translator' => false,
                            'is_translation_enabled' => false,
                            'profile_background_color' => '94D487',
                            'profile_background_image_url' => 'http://abs.twimg.com/images/themes/theme1/bg.png',
                            'profile_background_image_url_https' => 'https://abs.twimg.com/images/themes/theme1/bg.png',
                            'profile_background_tile' => false,
                            'profile_image_url' => 'http://pbs.twimg.com/profile_images/418236904778104833/Fvp3hQiE_normal.jpeg',
                            'profile_image_url_https' => 'https://pbs.twimg.com/profile_images/418236904778104833/Fvp3hQiE_normal.jpeg',
                            'profile_banner_url' => 'https://pbs.twimg.com/profile_banners/1664570156/1388550465',
                            'profile_link_color' => '3B94D9',
                            'profile_sidebar_border_color' => '000000',
                            'profile_sidebar_fill_color' => '000000',
                            'profile_text_color' => '000000',
                            'profile_use_background_image' => true,
                            'has_extended_profile' => true,
                            'default_profile' => false,
                            'default_profile_image' => false,
                            'following' => null,
                            'follow_request_sent' => null,
                            'notifications' => null,
                            'translator_type' => 'none',
                        ],
                    'geo' => null,
                    'coordinates' => null,
                    'place' => null,
                    'contributors' => null,
                    'retweeted_status' => [
                            'created_at' => 'Fri Jan 20 14:39:37 +0000 2017',
                            'id' => 822453533328801792,
                            'id_str' => '822453533328801792',
                            'text' => '“アプリファーストの影で頑張るWebの話 // Speaker Deck” https://t.co/2R5bmFVLZQ',
                            'truncated' => false,
                            'entities' => [
                                    'hashtags' => [
                                        ],
                                    'symbols' => [
                                        ],
                                    'user_mentions' => [
                                        ],
                                    'urls' => [
                                            0 => [
                                                    'url' => 'https://t.co/2R5bmFVLZQ',
                                                    'expanded_url' => 'http://htn.to/ec6kpX',
                                                    'display_url' => 'htn.to/ec6kpX',
                                                    'indices' => [
                                                            0 => 38,
                                                            1 => 61,
                                                        ],
                                                ],
                                        ],
                                ],
                            'source' => '<a href="http://www.hatena.ne.jp/guide/twitter" rel="nofollow">Hatena</a>',
                            'in_reply_to_status_id' => null,
                            'in_reply_to_status_id_str' => null,
                            'in_reply_to_user_id' => null,
                            'in_reply_to_user_id_str' => null,
                            'in_reply_to_screen_name' => null,
                            'user' => [
                                    'id' => 5707002,
                                    'id_str' => '5707002',
                                    'name' => 'Hiraku',
                                    'screen_name' => 'Hiraku',
                                    'location' => 'Kanagawa, Japan',
                                    'description' => 'PHPとかJavaScriptとか。最近はcomposer芸人を目指して研鑽中です。 https://t.co/OJCaxvyBxg の中の人',
                                    'url' => 'https://t.co/MhaZ82WTBw',
                                    'entities' => [
                                            'url' => [
                                                    'urls' => [
                                                            0 => [
                                                                    'url' => 'https://t.co/MhaZ82WTBw',
                                                                    'expanded_url' => 'http://blog.tojiru.net',
                                                                    'display_url' => 'blog.tojiru.net',
                                                                    'indices' => [
                                                                            0 => 0,
                                                                            1 => 23,
                                                                        ],
                                                                ],
                                                        ],
                                                ],
                                            'description' => [
                                                    'urls' => [
                                                            0 => [
                                                                    'url' => 'https://t.co/OJCaxvyBxg',
                                                                    'expanded_url' => 'http://packagist.jp',
                                                                    'display_url' => 'packagist.jp',
                                                                    'indices' => [
                                                                            0 => 43,
                                                                            1 => 66,
                                                                        ],
                                                                ],
                                                        ],
                                                ],
                                        ],
                                    'protected' => false,
                                    'followers_count' => 1475,
                                    'friends_count' => 854,
                                    'listed_count' => 91,
                                    'created_at' => 'Wed May 02 07:26:29 +0000 2007',
                                    'favourites_count' => 6162,
                                    'utc_offset' => 32400,
                                    'time_zone' => 'Tokyo',
                                    'geo_enabled' => true,
                                    'verified' => false,
                                    'statuses_count' => 23327,
                                    'lang' => 'ja',
                                    'contributors_enabled' => false,
                                    'is_translator' => false,
                                    'is_translation_enabled' => false,
                                    'profile_background_color' => '131516',
                                    'profile_background_image_url' => 'http://abs.twimg.com/images/themes/theme14/bg.gif',
                                    'profile_background_image_url_https' => 'https://abs.twimg.com/images/themes/theme14/bg.gif',
                                    'profile_background_tile' => true,
                                    'profile_image_url' => 'http://pbs.twimg.com/profile_images/1100290432/daemonicons_normal.jpg',
                                    'profile_image_url_https' => 'https://pbs.twimg.com/profile_images/1100290432/daemonicons_normal.jpg',
                                    'profile_banner_url' => 'https://pbs.twimg.com/profile_banners/5707002/1447791289',
                                    'profile_link_color' => '009999',
                                    'profile_sidebar_border_color' => 'EEEEEE',
                                    'profile_sidebar_fill_color' => 'EFEFEF',
                                    'profile_text_color' => '333333',
                                    'profile_use_background_image' => true,
                                    'has_extended_profile' => true,
                                    'default_profile' => false,
                                    'default_profile_image' => false,
                                    'following' => null,
                                    'follow_request_sent' => null,
                                    'notifications' => null,
                                    'translator_type' => 'none',
                                ],
                            'geo' => null,
                            'coordinates' => null,
                            'place' => null,
                            'contributors' => null,
                            'is_quote_status' => false,
                            'retweet_count' => 1,
                            'favorite_count' => 5,
                            'favorited' => false,
                            'retweeted' => false,
                            'possibly_sensitive' => false,
                            'lang' => 'ja',
                        ],
                    'is_quote_status' => false,
                    'retweet_count' => 1,
                    'favorite_count' => 0,
                    'favorited' => false,
                    'retweeted' => false,
                    'possibly_sensitive' => false,
                    'lang' => 'ja',
                ],
            2 => [
                    'created_at' => 'Sat Jan 21 04:36:14 +0000 2017',
                    'id' => 822664075339595776,
                    'id_str' => '822664075339595776',
                    'text' => '全然追って無かった… #CookpadTechConf',
                    'truncated' => false,
                    'entities' => [
                            'hashtags' => [
                                    0 => [
                                            'text' => 'CookpadTechConf',
                                            'indices' => [
                                                    0 => 11,
                                                    1 => 27,
                                                ],
                                        ],
                                ],
                            'symbols' => [
                                ],
                            'user_mentions' => [
                                ],
                            'urls' => [
                                ],
                        ],
                    'source' => '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
                    'in_reply_to_status_id' => null,
                    'in_reply_to_status_id_str' => null,
                    'in_reply_to_user_id' => null,
                    'in_reply_to_user_id_str' => null,
                    'in_reply_to_screen_name' => null,
                    'user' => [
                            'id' => 1664570156,
                            'id_str' => '1664570156',
                            'name' => 'Ryota Murakami',
                            'screen_name' => 'malloc007',
                            'location' => '東京都',
                            'description' => 'webエンジニアです。プログラミングについてのつぶやきが多いです。 IIDX中伝 4123-1440',
                            'url' => 'https://t.co/gc9H0nrlan',
                            'entities' => [
                                    'url' => [
                                            'urls' => [
                                                    0 => [
                                                            'url' => 'https://t.co/gc9H0nrlan',
                                                            'expanded_url' => 'http://ryota-murakami.github.io/',
                                                            'display_url' => 'ryota-murakami.github.io',
                                                            'indices' => [
                                                                    0 => 0,
                                                                    1 => 23,
                                                                ],
                                                        ],
                                                ],
                                        ],
                                    'description' => [
                                            'urls' => [
                                                ],
                                        ],
                                ],
                            'protected' => false,
                            'followers_count' => 279,
                            'friends_count' => 417,
                            'listed_count' => 21,
                            'created_at' => 'Mon Aug 12 08:50:15 +0000 2013',
                            'favourites_count' => 431,
                            'utc_offset' => 32400,
                            'time_zone' => 'Tokyo',
                            'geo_enabled' => true,
                            'verified' => false,
                            'statuses_count' => 6300,
                            'lang' => 'ja',
                            'contributors_enabled' => false,
                            'is_translator' => false,
                            'is_translation_enabled' => false,
                            'profile_background_color' => '94D487',
                            'profile_background_image_url' => 'http://abs.twimg.com/images/themes/theme1/bg.png',
                            'profile_background_image_url_https' => 'https://abs.twimg.com/images/themes/theme1/bg.png',
                            'profile_background_tile' => false,
                            'profile_image_url' => 'http://pbs.twimg.com/profile_images/418236904778104833/Fvp3hQiE_normal.jpeg',
                            'profile_image_url_https' => 'https://pbs.twimg.com/profile_images/418236904778104833/Fvp3hQiE_normal.jpeg',
                            'profile_banner_url' => 'https://pbs.twimg.com/profile_banners/1664570156/1388550465',
                            'profile_link_color' => '3B94D9',
                            'profile_sidebar_border_color' => '000000',
                            'profile_sidebar_fill_color' => '000000',
                            'profile_text_color' => '000000',
                            'profile_use_background_image' => true,
                            'has_extended_profile' => true,
                            'default_profile' => false,
                            'default_profile_image' => false,
                            'following' => null,
                            'follow_request_sent' => null,
                            'notifications' => null,
                            'translator_type' => 'none',
                        ],
                    'geo' => null,
                    'coordinates' => null,
                    'place' => null,
                    'contributors' => null,
                    'is_quote_status' => false,
                    'retweet_count' => 0,
                    'favorite_count' => 0,
                    'favorited' => false,
                    'retweeted' => false,
                    'lang' => 'ja',
                ],
        ];
    }
}
