---

- name: Install MySQL Server
  apt:
        name={{ item }}
        state=installed
  with_items:
        "{{ mysql_packages }}"

- name: Copy the my.cnf file
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
  notify:
   - Restart MySQL
