<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PastTimelineRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PastTimelineRepository extends EntityRepository
{
}
